mysql:
  image: kochiang99/docker_mysql
  environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
  volumes:
    - /srv/docker/redmine/mysql:/var/lib/mysql

redmine:
  image: kochiang99/docker_redmine
  #image: sameersbn/redmine:3.2.1
  links:
    - mysql:mysql
  environment:
    - TZ=Asia/Taipei

    - REDMINE_PORT=80
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUPS_DIR=/tmp/Backup
    - REDMINE_BACKUP_SCHEDULE=daily
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=00:00

    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=avermedia.com
    - SMTP_HOST=10.1.1.177
    - SMTP_PORT=25
    - SMTP_USER=
    - SMTP_PASS=
    - SMTP_STARTTLS=false
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    - NGINX_MAX_UPLOAD_SIZE=50m
    - UNICORN_TIMEOUT=600

  ports:
    - "8080:80"
    - "3000:3000"
  volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
    - /tmp/Backup.tmp:/tmp/Backup
    - /home/redmine/git:/GIT
